export const DELETE_ENTITY_START = 'DELETE_ENTITY_START';
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_FAILURE = 'DELETE_ENTITY_FAILURE';
export const DELETE_ENTITY_RESET = 'DELETE_ENTITY_RESET';
