export const CREATE_ENTITY_START = 'CREATE_ENTITY_START';
export const CREATE_ENTITY_SUCCESS = 'CREATE_ENTITY_SUCCESS';
export const CREATE_ENTITY_FAILURE = 'CREATE_ENTITY_FAILURE';
export const CREATE_ENTITY_RESET = 'CREATE_ENTITY_RESET';
