export const UPDATE_ENTITY_START = 'UPDATE_ENTITY_START';
export const UPDATE_ENTITY_SUCCESS = 'UPDATE_ENTITY_SUCCESS';
export const UPDATE_ENTITY_FAILURE = 'UPDATE_ENTITY_FAILURE';
export const UPDATE_ENTITY_RESET = 'UPDATE_ENTITY_RESET';
