export const LIST_ENTITIES_START = 'LIST_ENTITIES_START';
export const LIST_ENTITIES_SUCCESS = 'LIST_ENTITIES_SUCCESS';
export const LIST_ENTITIES_FAILURE = 'LIST_ENTITIES_FAILURE';
export const LIST_MORE_ENTITIES = 'LIST_MORE_ENTITIES';
export const UPDATE_PAGE_CURSOR = 'UPDATE_PAGE_CURSOR';
